### ISSUE TITLE
Add support for Python 3

### ISSUE THREAD

**Issue by reinhardt** [plone/plone.app.form#15]
Are there plans to support python 3?

**Comment by alecghica** [comment]
@reinhardt there is a branch for Python 3. I'll check it soon and let u know. :)

**Comment by alecghica** [comment]
@reinhardt I fixed some Python 3 issues and it now the Plone instance starts. There are still things to be fixed, like tests.

**Comment by reinhardt** [comment]
Awesome, thanks!

**Comment by alecghica** [comment]
@reinhardt I also didn't tested if really works as it is for now. My priority for now was to make the Plone instance start with the add-on installed. If you give it a try and find problems add issues or fix them directly! :)

**Comment by alecghica** [comment]
I think this issue can be closed, there is a [python3](https://github.com/plone/plone.app.form/tree/python3) branch. The instance using Plone 5.2 & Python 3 starts if it used. Nevertheless that branch need more attention.
