### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by laulaz** [plone/plone.app.form#16]
Hi,

is it possible to release a new version of this package (or give me rights to do so on Pypi - user : laz) ? @tisto maybe ?
CMFDefault dependency leads to `ConfigurationConflictError` in Plone 5.2.1 with `zope.formlib` and `five.formlib`.

Thank you very much !

**Comment by mauritsvanrees** [comment]
I have released `plone.app.form` 1.1.10 and 2.3.3.
I don't think you should use this with Plone 5.2, but you can try if you want.
