### ISSUE TITLE
ceiling might be reached soon-ish ;)

### ISSUE THREAD

**Issue by iham** [plone/plone.app.form#17]
also here: greetings from @gogobd 

that ceiling is a problem now:
https://github.com/plone/plone.app.form/blob/2.2.x/plone/app/form/widgets/datecomponents.py#L16

on older plones, this package is still in use and hits the same error
https://github.com/plone/Products.Archetypes/issues/133

**Comment by mauritsvanrees** [comment]
For Archetypes I see the problem, but not here in `plone.app.form`: the line you point to has a ceiling of 2500. Am I missing something?

**Comment by iham** [comment]
@mauritsvanrees you are right - i need to check our env.
because i am not sure, if our Products.Archetypes 1.15.7 (a plone 3.3.6) would be able to handle a 2.2.x release of plone.app.form. (do you have any xp on that topic).

if it would work, we might be able to pin plone.app.form to a newer version and we might be good to go...
(@gogobd might give it a shot)

**Comment by mauritsvanrees** [comment]
It is doubtful that 2.2.x would work on Plone 3. I suspect it will pull in too new packages. But you can try.

If you only want to try 2.2.x for the updated `PLONE_CEILING`, which is the soonish 2021 in the [1.1 branch](https://github.com/plone/plone.app.form/blob/1.1/plone/app/form/widgets/datecomponents.py), then it would seem better if you fix it on the 1.1 branch.
I could make a release of that.

Or you do a monkey patch in a site specific package. Or you make an internal release.

**Comment by iham** [comment]
@mauritsvanrees thanks for your insight!

i lifted the ceiling to 2050 on the 1.1 branch.

can u release that one?

**Comment by mauritsvanrees** [comment]
I have released `plone.app.form` 1.1.10. Have fun!
