### ISSUE TITLE
Localization issue in datecomponents.DateComponents view

### ISSUE THREAD

**Issue by keul** [plone/plone.app.form#8]
I found a weird bug in `DateComponents` on branch 2.1.x (Plone 4.2) and 2.2.x (Plone 4.3).
On master the view had been removed so I don't know if this can happen also on Plone 5.

Issue happen at [that line] (https://github.com/plone/plone.app.form/blob/f00d3d179f34b52ab9f5c1fc8c7c4247edd09c31/plone/app/form/widgets/datecomponents.py#L218) where the current result from a call to `date.strftime("%p")` is compared to `"AM"` on `"PM"`:

    if x==p and not default:
        ...

But when some locales are set (for example IT_it, or DE_de) the call to `.format` will return `"am"` or `"pm"` (lowercase).
Normally Plone or buildout do not set locales directly but some 3rd party code can do this. For example: installing collective.flowplayer will also install the evil `hachoir_core` that call `locale.setlocale(locale.LC_ALL, "")` somewhere.

Apart the way to reproduce the issue, I think that a case insensitive version can make this code more robust:

    if x.lower()==p.lower() and not default:
        ...

Another way to test the issue simply using python:

    >>> from datetime import datetime
    >>> import locale
    >>> datetime.now().strftime("%p")
    'PM'
    >>> locale.setlocale(locale.LC_TIME, "IT_it")
    'IT_it'
    >>> datetime.now().strftime("%p")
    'pm'

Any thought? If is OK I'd like to make a PR for this.

**Comment by keul** [comment]
...sorry: forgot to mention the *real* issue for final user.

When editing a content types with a DateTime field the "AM/PM" combobox if not initialized with the right date, so a user can't know if the saved date is (for example) 5:00 AM on PM as is always see "5:00 --"

![schermata 2015-04-16 a 17 19 27](https://cloud.githubusercontent.com/assets/284924/7184284/c8b9e32c-e45c-11e4-9e6d-2f0d081e4bad.png)

**Comment by keul** [comment]
@gforcada thanks for looking into this.

Sadly seems that fixing this providing a coverage test case is above my power and the time the custom can pay for this.

**Comment by jensens** [comment]
@keul, looks like this one was solved meanhwile. I close it, feel free to reopen if i'am wrong.
